spring.application.name=muse-server

app.jwt.secret=yourSuperSecretKeyForJWTTokenGeneration1234567890
app.jwt.expiration=86400000

app.cors.allowed-origins=http://localhost:5173

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/muse_db
spring.datasource.username=muse_root
spring.datasource.password=muse_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.com.muse.server=DEBUG